(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val accounts_address_get : address:string -> ?block_height:Block_height.t -> unit -> Account.t Lwt.t
