(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let events_get ~_type ?start_height ?end_height ?(block_ids = []) ?(select = []) () =
    let open Lwt in
    let uri = Request.build_uri "/events" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "type" (fun x -> x) _type in
    let uri = Request.maybe_add_query_param uri "start_height" .show start_height in
    let uri = Request.maybe_add_query_param uri "end_height" .show end_height in
    let uri = Request.add_query_param_list uri "block_ids" (List.map (fun x -> x)) block_ids in
    let uri = Request.add_query_param_list uri "select" (List.map (fun x -> x)) select in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Block_events.of_yojson) resp body

