(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val events_get : _type:string -> ?start_height:Block_height.t -> ?end_height:Block_height.t -> ?block_ids:string list -> ?select:string list -> unit -> Block_events.t Lwt.t
