(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val scripts_post : inline_object_1_t:Inline_object_1.t -> ?block_id:string -> ?block_height:Block_height.t -> unit -> Inline_response_200.t Lwt.t
