(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val transaction_results_transaction_id_get : transaction_id:string -> ?expand:string list -> ?select:string list -> unit -> Transaction_result.t Lwt.t
val transactions_id_get : id:string -> ?expand:string list -> ?select:string list -> unit -> Transaction.t Lwt.t
val transactions_post : inline_object_t:Inline_object.t -> Transaction.t Lwt.t
