(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    keys: string option [@default None];
    contracts: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    keys = None;
    contracts = None;
}

