(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Index of the public key. *)
    index: string;
    (* Hex encoded public key. *)
    public_key: string;
    signing_algorithm: Enums.signingalgorithm;
    hashing_algorithm: Enums.hashingalgorithm;
    (* Current account sequence number. *)
    sequence_number: string;
    (* Weight of the key. *)
    weight: string;
    (* Flag indicating whether the key is active or not. *)
    revoked: bool;
} [@@deriving yojson { strict = false }, show ];;

let create (index : string) (public_key : string) (signing_algorithm : Enums.signingalgorithm) (hashing_algorithm : Enums.hashingalgorithm) (sequence_number : string) (weight : string) (revoked : bool) : t = {
    index = index;
    public_key = public_key;
    signing_algorithm = signing_algorithm;
    hashing_algorithm = hashing_algorithm;
    sequence_number = sequence_number;
    weight = weight;
    revoked = revoked;
}

