(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The 8-byte address of an account. *)
    address: string;
    (* Flow balance of the account. *)
    balance: string;
    keys: Account_public_key.t list option [@default None];
    contracts: (string * string) list option [@default None];
    _expandable: Account__expandable.t;
    _links: Links.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (address : string) (balance : string) (_expandable : Account__expandable.t) : t = {
    address = address;
    balance = balance;
    keys = Some [];
    contracts = Some [];
    _expandable = _expandable;
    _links = None;
}

