(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    verifier_signatures: string list;
    signer_ids: string list;
} [@@deriving yojson { strict = false }, show ];;

let create (verifier_signatures : string list) (signer_ids : string list) : t = {
    verifier_signatures = verifier_signatures;
    signer_ids = signer_ids;
}

