(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    collection_guarantees: Collection_guarantee.t list;
    block_seals: Block_seal.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (collection_guarantees : Collection_guarantee.t list) (block_seals : Block_seal.t list) : t = {
    collection_guarantees = collection_guarantees;
    block_seals = block_seals;
}

