(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    payload: string option [@default None];
    execution_result: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    payload = None;
    execution_result = None;
}

