(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* A 32-byte unique identifier for an entity. *)
    block_id: string option [@default None];
    block_height: string option [@default None];
    block_timestamp: string option [@default None];
    events: Event.t list;
    _links: Links.t option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    block_id = None;
    block_height = None;
    block_timestamp = None;
    events = [];
    _links = None;
}

