(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* A 32-byte unique identifier for an entity. *)
    collection_id: string;
    signer_ids: string list;
    (* A variable length signature. *)
    signature: string;
} [@@deriving yojson { strict = false }, show ];;

let create (collection_id : string) (signer_ids : string list) (signature : string) : t = {
    collection_id = collection_id;
    signer_ids = signer_ids;
    signature = signature;
}

