(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Base64 encoded content of the Cadence script. *)
    script: string;
    (* A list of arguments each encoded as Base64 passed in the [JSON-Cadence interchange format](https://docs.onflow.org/cadence/json-cadence-spec/). *)
    arguments: string list;
    (* A 32-byte unique identifier for an entity. *)
    reference_block_id: string;
    (* The limit on the amount of computation a transaction is allowed to preform. *)
    gas_limit: string;
    (* The 8-byte address of an account. *)
    payer: string;
    proposal_key: Proposal_key.t;
    authorizers: string list;
    (* A list of Base64 encoded signatures. *)
    payload_signatures: Transaction_signature.t list;
    (* A list of Base64 encoded signatures. *)
    envelope_signatures: Transaction_signature.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (script : string) (arguments : string list) (reference_block_id : string) (gas_limit : string) (payer : string) (proposal_key : Proposal_key.t) (authorizers : string list) (payload_signatures : Transaction_signature.t list) (envelope_signatures : Transaction_signature.t list) : t = {
    script = script;
    arguments = arguments;
    reference_block_id = reference_block_id;
    gas_limit = gas_limit;
    payer = payer;
    proposal_key = proposal_key;
    authorizers = authorizers;
    payload_signatures = payload_signatures;
    envelope_signatures = envelope_signatures;
}

