(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* Base64 encoded content of the Cadence script. *)
    script: string option [@default None];
    (* An list of arguments each encoded as Base64 passed in the [JSON-Cadence interchange format](https://docs.onflow.org/cadence/json-cadence-spec/). *)
    arguments: string list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    script = None;
    arguments = [];
}

