(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The 8-byte address of an account. *)
    address: string;
    key_index: string;
    sequence_number: string;
} [@@deriving yojson { strict = false }, show ];;

let create (address : string) (key_index : string) (sequence_number : string) : t = {
    address = address;
    key_index = key_index;
    sequence_number = sequence_number;
}

