(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Transaction_signature.t : Base64 encoded signature.
 *)

type t = {
    (* The 8-byte address of an account. *)
    address: string;
    key_index: string;
    (* A variable length signature. *)
    signature: string;
} [@@deriving yojson { strict = false }, show ];;

(** Base64 encoded signature. *)
let create (address : string) (key_index : string) (signature : string) : t = {
    address = address;
    key_index = key_index;
    signature = signature;
}

