lib: [
  "_build/install/default/lib/ocaml_flow_sdk/META"
  "_build/install/default/lib/ocaml_flow_sdk/dune-package"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.a"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cma"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cmi"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cmt"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cmx"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cmxa"
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.ml"
  "_build/install/default/lib/ocaml_flow_sdk/opam"
]
libexec: [
  "_build/install/default/lib/ocaml_flow_sdk/ocaml_flow_sdk.cmxs"
]
